/**
 * Script de seed para poblar la base de datos con datos de ejemplo
 * Ejecutar: npx tsx prisma/seed.ts
 */

import dotenv from 'dotenv';

// Cargar variables de entorno ANTES de usar process.env
dotenv.config();

import { PrismaClient } from '../src/generated/prisma/client';
import { OperationType, PropertyCategory, PropertyStatus } from '../src/generated/prisma/enums';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({
  adapter,
});

async function main() {
  console.log('🌱 Iniciando seed de la base de datos...\n');

  // Verificar que existan las ciudades necesarias
  const madrid = await prisma.city.findFirst({ where: { slug: 'madrid' } });
  const barcelona = await prisma.city.findFirst({ where: { slug: 'barcelona' } });
  const sevilla = await prisma.city.findFirst({ where: { slug: 'sevilla' } });
  const valencia = await prisma.city.findFirst({ where: { slug: 'valencia' } });

  if (!madrid || !barcelona || !sevilla || !valencia) {
    console.error('❌ Error: Asegúrate de que existan las ciudades Madrid, Barcelona, Sevilla y Valencia');
    console.log('Ejecuta primero el panel admin para crear las ciudades.');
    return;
  }

  console.log('✅ Ciudades encontradas\n');

  // Propiedades de ejemplo
  const properties = [
    // MADRID
    {
      title: 'Piso exclusivo en Salamanca',
      slug: 'piso-exclusivo-salamanca-seed',
      description: 'Espectacular piso de lujo en el barrio de Salamanca. Totalmente reformado con materiales de primera calidad. Cuenta con amplios espacios, mucha luz natural y acabados excepcionales. Ideal para familias que buscan el máximo confort en una de las mejores zonas de Madrid.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 450000,
      cityId: madrid.id,
      neighborhood: 'Salamanca',
      address: 'Calle Serrano 125',
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 120,
      builtYear: 2018,
      floor: 4,
      hasElevator: true,
      hasParking: true,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Ático con terraza panorámica',
      slug: 'atico-terraza-panoramica-seed',
      description: 'Impresionante ático en el centro de Madrid con terraza de 80m². Vistas despejadas a toda la ciudad. Diseño moderno y funcional con cocina americana totalmente equipada. Perfecto para quienes valoran los espacios exteriores.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.PENTHOUSE,
      price: 650000,
      cityId: madrid.id,
      neighborhood: 'Centro',
      address: 'Gran Vía 42',
      bedrooms: 4,
      bathrooms: 3,
      areaM2: 150,
      builtYear: 2020,
      floor: 8,
      hasElevator: true,
      hasParking: true,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: true,
      petsAllowed: true,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Estudio moderno en Malasaña',
      slug: 'estudio-moderno-malasana-seed',
      description: 'Acogedor estudio completamente amueblado en pleno corazón de Malasaña. Perfecto para estudiantes o jóvenes profesionales. Zona con excelente ambiente, cerca de metro y todos los servicios.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.STUDIO,
      price: 850,
      cityId: madrid.id,
      neighborhood: 'Malasaña',
      address: 'Calle del Pez 15',
      bedrooms: 1,
      bathrooms: 1,
      areaM2: 35,
      floor: 2,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: true,
      petsAllowed: false,
      energyRating: 'D',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    // BARCELONA
    {
      title: 'Piso modernista en Eixample',
      slug: 'piso-modernista-eixample-seed',
      description: 'Excepcional piso en finca modernista rehabilitada. Techos altos con molduras originales, suelos hidráulicos restaurados y mucha luz natural. Combina el encanto histórico con las comodidades modernas.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 520000,
      cityId: barcelona.id,
      neighborhood: 'Eixample',
      address: 'Passeig de Gràcia 88',
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 110,
      builtYear: 1920,
      floor: 3,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Chalet con piscina en Castelldefels',
      slug: 'chalet-piscina-castelldefels-seed',
      description: 'Magnífico chalet independiente a 5 minutos de la playa. Amplio jardín con piscina privada, porche cubierto y zona BBQ. Ideal para familias que buscan tranquilidad sin renunciar a la cercanía del mar.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.HOUSE,
      price: 890000,
      cityId: barcelona.id,
      neighborhood: 'Castelldefels',
      address: 'Avenida del Mar 234',
      bedrooms: 5,
      bathrooms: 3,
      areaM2: 280,
      builtYear: 2015,
      hasElevator: false,
      hasParking: true,
      hasPool: true,
      hasTerrace: false,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Loft industrial en Poblenou',
      slug: 'loft-industrial-poblenou-seed',
      description: 'Espectacular loft de diseño en antiguo edificio industrial rehabilitado. Espacios diáfanos con doble altura, grandes ventanales y acabados de calidad. Perfecto para creativos y amantes del diseño contemporáneo.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.FLAT,
      price: 1800,
      cityId: barcelona.id,
      neighborhood: 'Poblenou',
      address: 'Carrer de Llull 50',
      bedrooms: 2,
      bathrooms: 2,
      areaM2: 95,
      builtYear: 2019,
      floor: 1,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: true,
      petsAllowed: true,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    // SEVILLA
    {
      title: 'Casa tradicional en Triana',
      slug: 'casa-tradicional-triana-seed',
      description: 'Encantadora casa andaluza completamente reformada en el corazón de Triana. Patio interior típico sevillano con fuente, azulejos originales y mucha personalidad. Una joya arquitectónica que respeta la esencia del barrio.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.HOUSE,
      price: 385000,
      cityId: sevilla.id,
      neighborhood: 'Triana',
      address: 'Calle Betis 76',
      bedrooms: 4,
      bathrooms: 3,
      areaM2: 180,
      builtYear: 1950,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Piso histórico junto a la Catedral',
      slug: 'piso-historico-catedral-seed',
      description: 'Piso señorial en edificio histórico a dos pasos de la Catedral y la Giralda. Techos altos, balcones con vistas y elementos arquitectónicos originales. Ubicación inmejorable en pleno casco antiguo.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 295000,
      cityId: sevilla.id,
      neighborhood: 'Casco Antiguo',
      address: 'Calle Mateos Gago 12',
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 95,
      builtYear: 1890,
      floor: 2,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      energyRating: 'D',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Dúplex moderno en Nervión',
      slug: 'duplex-moderno-nervion-seed',
      description: 'Dúplex de reciente construcción en zona residencial tranquila. Distribución perfecta en dos plantas, terraza privada en planta superior y plaza de garaje. Ideal para familias.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.DUPLEX,
      price: 1200,
      cityId: sevilla.id,
      neighborhood: 'Nervión',
      address: 'Avenida Luis de Morales 34',
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 115,
      builtYear: 2021,
      floor: 4,
      hasElevator: true,
      hasParking: true,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    // VALENCIA
    {
      title: 'Apartamento frente al mar en Malvarrosa',
      slug: 'apartamento-mar-malvarrosa-seed',
      description: 'Espectacular apartamento en primera línea de playa con vistas panorámicas al Mediterráneo. Amplia terraza orientada al mar, cocina equipada y acabados de lujo. Vive frente al mar todo el año.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 420000,
      cityId: valencia.id,
      neighborhood: 'La Malvarrosa',
      address: 'Paseo Marítimo 156',
      bedrooms: 2,
      bathrooms: 2,
      areaM2: 85,
      builtYear: 2017,
      floor: 6,
      hasElevator: true,
      hasParking: true,
      hasPool: true,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Piso reformado en el Carmen',
      slug: 'piso-reformado-carmen-seed',
      description: 'Piso completamente reformado en el vibrante barrio del Carmen. Combina elementos tradicionales con diseño moderno. Cerca de todos los servicios, restaurantes y vida cultural del centro histórico.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 280000,
      cityId: valencia.id,
      neighborhood: 'El Carmen',
      address: 'Calle Caballeros 45',
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 75,
      builtYear: 2022,
      floor: 1,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Villa de lujo con piscina infinita',
      slug: 'villa-lujo-piscina-infinita-seed',
      description: 'Impresionante villa de diseño contemporáneo con piscina infinity y vistas panorámicas. Domótica completa, gimnasio privado y jardines cuidados. El máximo lujo y confort en una ubicación privilegiada.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.VILLA,
      price: 3500,
      cityId: valencia.id,
      neighborhood: 'La Cañada',
      address: 'Urbanización El Pinar 8',
      bedrooms: 4,
      bathrooms: 4,
      areaM2: 350,
      builtYear: 2020,
      hasElevator: false,
      hasParking: true,
      hasPool: true,
      hasTerrace: false,
      hasGarden: true,
      furnished: true,
      petsAllowed: true,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Piso cerca de la Universidad',
      slug: 'piso-cerca-universidad-seed',
      description: 'Piso funcional y bien ubicado cerca del campus universitario. Perfecto para estudiantes o jóvenes profesionales. Zona tranquila con buenas conexiones de transporte público.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.FLAT,
      price: 650,
      cityId: valencia.id,
      neighborhood: 'Benimaclet',
      address: 'Calle Alboraya 89',
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 60,
      floor: 3,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: true,
      petsAllowed: false,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    // MÁS PROPIEDADES VARIADAS
    // Madrid - Más opciones
    {
      title: 'Oficina luminosa en Cuatro Caminos',
      slug: 'oficina-luminosa-cuatro-caminos-seed',
      description: 'Amplia oficina diáfana lista para entrar. Excelente ubicación con gran visibilidad y acceso directo a transporte público. Perfecta para startups o pequeños equipos.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.OFFICE,
      price: 1500,
      cityId: madrid.id,
      neighborhood: 'Cuatro Caminos',
      address: 'Paseo de la Castellana 210',
      areaM2: 85,
      builtYear: 2010,
      floor: 2,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Local comercial en Chueca',
      slug: 'local-comercial-chueca-seed',
      description: 'Local a pie de calle en una de las zonas más comerciales de Madrid. Gran escaparate, almacén y baño. Ideal para tienda, cafetería o showroom.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.COMMERCIAL,
      price: 2200,
      cityId: madrid.id,
      neighborhood: 'Chueca',
      address: 'Calle Hortaleza 56',
      areaM2: 70,
      floor: 0,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      energyRating: 'D',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Garaje doble en Retiro',
      slug: 'garaje-doble-retiro-seed',
      description: 'Plaza de garaje doble con trastero incluido. Acceso directo desde calle, muy fácil de aparcar. Portón automático y vigilancia 24h.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.GARAGE,
      price: 180,
      cityId: madrid.id,
      neighborhood: 'Retiro',
      address: 'Calle O\'Donnell 34',
      areaM2: 30,
      hasElevator: false,
      hasParking: true,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Chalet adosado en Las Rozas',
      slug: 'chalet-adosado-las-rozas-seed',
      description: 'Precioso chalet adosado en urbanización privada. Jardín privado, piscina comunitaria, zonas deportivas y parque infantil. A 20 minutos del centro de Madrid.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.TOWNHOUSE,
      price: 485000,
      cityId: madrid.id,
      neighborhood: 'Las Rozas',
      address: 'Urbanización Monte Rozas',
      bedrooms: 4,
      bathrooms: 3,
      areaM2: 200,
      builtYear: 2016,
      hasElevator: false,
      hasParking: true,
      hasPool: true,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    // Barcelona - Más opciones
    {
      title: 'Estudio en Gràcia',
      slug: 'estudio-gracia-seed',
      description: 'Pequeño pero encantador estudio en el bohemio barrio de Gràcia. Reformado recientemente, muy luminoso. Perfecto para una persona o pareja.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.STUDIO,
      price: 750,
      cityId: barcelona.id,
      neighborhood: 'Gràcia',
      address: 'Carrer de Verdi 42',
      bedrooms: 1,
      bathrooms: 1,
      areaM2: 32,
      builtYear: 2021,
      floor: 3,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: true,
      petsAllowed: false,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Ático dúplex en Born',
      slug: 'atico-duplex-born-seed',
      description: 'Espectacular ático dúplex en pleno Born. Terraza de 60m² con vistas a Santa María del Mar. Diseño exclusivo con materiales de alta gama.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.DUPLEX,
      price: 780000,
      cityId: barcelona.id,
      neighborhood: 'El Born',
      address: 'Carrer Montcada 18',
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 135,
      builtYear: 2019,
      floor: 5,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Trastero en Sants',
      slug: 'trastero-sants-seed',
      description: 'Trastero amplio y seco en edificio con vigilancia. Perfecto para almacenar muebles, bicicletas o hacer un pequeño taller.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.WAREHOUSE,
      price: 85,
      cityId: barcelona.id,
      neighborhood: 'Sants',
      address: 'Carrer de Sants 234',
      areaM2: 15,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    // Sevilla - Más opciones
    {
      title: 'Piso con patio en Alameda',
      slug: 'piso-patio-alameda-seed',
      description: 'Bonito piso con patio privado de 40m². Recién reformado manteniendo el estilo andaluz tradicional. Aire acondicionado y cocina nueva.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.FLAT,
      price: 950,
      cityId: sevilla.id,
      neighborhood: 'Alameda',
      address: 'Calle Amor de Dios 12',
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 80,
      builtYear: 1960,
      floor: 1,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'D',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Nave industrial en Polígono Store',
      slug: 'nave-industrial-poligono-store-seed',
      description: 'Nave industrial con oficinas, zona de carga y descarga. Altura libre de 6 metros. Ideal para logística o almacenamiento.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.INDUSTRIAL,
      price: 1800,
      cityId: sevilla.id,
      neighborhood: 'Polígono Store',
      address: 'Calle Astronomía 45',
      areaM2: 350,
      builtYear: 2005,
      hasElevator: false,
      hasParking: true,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      energyRating: 'E',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Villa en Aljarafe',
      slug: 'villa-aljarafe-seed',
      description: 'Exclusiva villa de diseño con vistas panorámicas. Piscina infinity, jardín mediterráneo de 500m², bodega climatizada y spa privado. Lujo absoluto.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.VILLA,
      price: 1250000,
      cityId: sevilla.id,
      neighborhood: 'Aljarafe',
      address: 'Urbanización La Juliana',
      bedrooms: 5,
      bathrooms: 4,
      areaM2: 420,
      builtYear: 2018,
      hasElevator: false,
      hasParking: true,
      hasPool: true,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    // Valencia - Más opciones
    {
      title: 'Piso en Ruzafa con ascensor',
      slug: 'piso-ruzafa-ascensor-seed',
      description: 'Piso reformado en Ruzafa, el barrio más de moda de Valencia. Balcón a la calle, cocina equipada y aire acondicionado. Rodeado de restaurantes y tiendas.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.FLAT,
      price: 1100,
      cityId: valencia.id,
      neighborhood: 'Ruzafa',
      address: 'Calle Sueca 28',
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 70,
      builtYear: 2020,
      floor: 3,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Casa de campo en La Eliana',
      slug: 'casa-campo-la-eliana-seed',
      description: 'Preciosa casa de campo rodeada de naturaleza. Gran terreno con árboles frutales, piscina, barbacoa y zona de huerto. Tranquilidad a 15 minutos de Valencia.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.HOUSE,
      price: 395000,
      cityId: valencia.id,
      neighborhood: 'La Eliana',
      address: 'Camino Viejo de Liria',
      bedrooms: 4,
      bathrooms: 2,
      areaM2: 180,
      builtYear: 1995,
      hasElevator: false,
      hasParking: true,
      hasPool: true,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'D',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Oficina en Campanar',
      slug: 'oficina-campanar-seed',
      description: 'Moderna oficina en edificio de nueva construcción. Instalaciones de última generación, climatización, internet de alta velocidad. Parking incluido.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.OFFICE,
      price: 1300,
      cityId: valencia.id,
      neighborhood: 'Campanar',
      address: 'Avenida Cortes Valencianas 58',
      areaM2: 95,
      builtYear: 2022,
      floor: 4,
      hasElevator: true,
      hasParking: true,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
  ];

  // Crear propiedades
  console.log('📝 Creando propiedades...\n');

  for (const property of properties) {
    try {
      const created = await prisma.property.create({
        data: property,
      });
      console.log(`✅ ${created.title} - ${created.operation === 'SALE' ? '€' + created.price.toLocaleString() : '€' + created.price + '/mes'}`);
    } catch (error: any) {
      if (error.code === 'P2002') {
        console.log(`⚠️  ${property.title} - Ya existe (slug duplicado)`);
      } else {
        console.error(`❌ Error al crear ${property.title}:`, error.message);
      }
    }
  }

  console.log('\n✅ Seed completado!');
  console.log(`📊 Total de propiedades destacadas: ${properties.filter(p => p.isFeatured).length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error durante el seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
