/**
 * Script de seed para poblar la base de datos con datos de ejemplo
 * 20 propiedades en Sanlúcar de Barrameda con coordenadas GPS reales
 * Ejecutar: npx tsx prisma/seed-sanlucar.ts
 */

import dotenv from 'dotenv';

// Cargar variables de entorno ANTES de usar process.env
dotenv.config();

import { PrismaClient } from '../src/generated/prisma/client';
import { OperationType, PropertyCategory, PropertyStatus } from '../src/generated/prisma/enums';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({
  adapter,
});

// Coordenadas de los barrios de Sanlúcar de Barrameda
const BARRIOS = {
  BARRIO_BAJO: { lat: 36.7748, lng: -6.3536, name: 'Barrio Bajo' },
  BARRIO_ALTO: { lat: 36.7812, lng: -6.3502, name: 'Barrio Alto' },
  LA_JARA: { lat: 36.7689, lng: -6.3421, name: 'La Jara' },
  MARTIN_MIGUEL: { lat: 36.7765, lng: -6.3458, name: 'Martín Miguel' },
  EL_PINO: { lat: 36.7698, lng: -6.3565, name: 'El Pino' },
};

// Función para generar pequeñas variaciones en las coordenadas
function randomOffset(base: number, maxOffset: number = 0.003): number {
  return base + (Math.random() - 0.5) * maxOffset;
}

async function main() {
  console.log('🌱 Iniciando seed de la base de datos...\n');
  console.log('🧹 Limpiando datos existentes...');

  // Limpiar tablas en orden correcto (por dependencias)
  await prisma.propertyImage.deleteMany();
  await prisma.property.deleteMany();
  await prisma.city.deleteMany();

  console.log('✅ Datos limpiados\n');

  // Crear la ciudad de Sanlúcar de Barrameda
  console.log('🏙️ Creando ciudad de Sanlúcar de Barrameda...');
  const sanlucar = await prisma.city.create({
    data: {
      name: 'Sanlúcar de Barrameda',
      slug: 'sanlucar-de-barrameda',
      province: 'Cádiz',
      active: true,
      latitude: 36.7781,
      longitude: -6.3515,
    },
  });
  console.log(`✅ Ciudad creada: ${sanlucar.name}\n`);

  // 20 Propiedades en Sanlúcar de Barrameda
  const properties = [
    // === BARRIO BAJO (zona cercana al río y playa) ===
    {
      title: 'Piso luminoso en Barrio Bajo',
      slug: 'piso-luminoso-barrio-bajo',
      description: 'Precioso piso completamente reformado a 5 minutos andando de la playa. Orientación sur con mucha luz natural. Cocina americana equipada, aire acondicionado y suelos de tarima. Zona muy tranquila y familiar.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 125000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.BARRIO_BAJO.name,
      address: 'Calle Ancha 45',
      latitude: randomOffset(BARRIOS.BARRIO_BAJO.lat),
      longitude: randomOffset(BARRIOS.BARRIO_BAJO.lng),
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 95,
      builtYear: 2010,
      floor: 2,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Apartamento con vistas al Guadalquivir',
      slug: 'apartamento-vistas-guadalquivir',
      description: 'Espectacular apartamento en primera línea del río Guadalquivir con vistas a Doñana. Terraza de 15m² orientada al atardecer. Totalmente reformado con materiales de alta calidad.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.APARTMENT,
      price: 185000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.BARRIO_BAJO.name,
      address: 'Paseo Marítimo 12',
      latitude: randomOffset(BARRIOS.BARRIO_BAJO.lat),
      longitude: randomOffset(BARRIOS.BARRIO_BAJO.lng),
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 75,
      builtYear: 2018,
      floor: 4,
      hasElevator: true,
      hasParking: true,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: true,
      petsAllowed: false,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Estudio cerca de Bajo de Guía',
      slug: 'estudio-bajo-guia',
      description: 'Acogedor estudio ideal para inversión o primera vivienda. A 3 minutos de los famosos restaurantes de Bajo de Guía. Perfecto para disfrutar del ambiente marinero de Sanlúcar.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.FLAT,
      price: 450,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.BARRIO_BAJO.name,
      address: 'Calle Bolsa 8',
      latitude: randomOffset(BARRIOS.BARRIO_BAJO.lat),
      longitude: randomOffset(BARRIOS.BARRIO_BAJO.lng),
      bedrooms: 1,
      bathrooms: 1,
      areaM2: 40,
      builtYear: 2005,
      floor: 1,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: true,
      petsAllowed: false,
      energyRating: 'D',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Casa tradicional andaluza en Barrio Bajo',
      slug: 'casa-tradicional-barrio-bajo',
      description: 'Encantadora casa tradicional con patio andaluz típico. Conserva elementos originales como azulejos y techos de madera. Reformada manteniendo su esencia histórica.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.HOUSE,
      price: 220000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.BARRIO_BAJO.name,
      address: 'Calle Caballeros 23',
      latitude: randomOffset(BARRIOS.BARRIO_BAJO.lat),
      longitude: randomOffset(BARRIOS.BARRIO_BAJO.lng),
      bedrooms: 4,
      bathrooms: 2,
      areaM2: 150,
      builtYear: 1920,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'E',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },

    // === BARRIO ALTO (zona histórica, Castillo de Santiago) ===
    {
      title: 'Ático con terraza en Barrio Alto',
      slug: 'atico-terraza-barrio-alto',
      description: 'Impresionante ático con terraza de 40m² y vistas panorámicas al casco histórico y al río. Zona privilegiada junto al Castillo de Santiago. Reforma integral reciente.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.PENTHOUSE,
      price: 265000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.BARRIO_ALTO.name,
      address: 'Plaza del Castillo 5',
      latitude: randomOffset(BARRIOS.BARRIO_ALTO.lat),
      longitude: randomOffset(BARRIOS.BARRIO_ALTO.lng),
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 110,
      builtYear: 2015,
      floor: 4,
      hasElevator: true,
      hasParking: true,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Piso en calle peatonal del centro',
      slug: 'piso-calle-peatonal-centro',
      description: 'Piso en pleno centro histórico, en calle peatonal. A un paso de todos los comercios, bares y restaurantes. Ideal para quien busca vivir el día a día sanluqueño.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.FLAT,
      price: 550,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.BARRIO_ALTO.name,
      address: 'Calle San Juan 18',
      latitude: randomOffset(BARRIOS.BARRIO_ALTO.lat),
      longitude: randomOffset(BARRIOS.BARRIO_ALTO.lng),
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 65,
      builtYear: 1990,
      floor: 2,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: true,
      petsAllowed: false,
      energyRating: 'D',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Dúplex moderno en Barrio Alto',
      slug: 'duplex-moderno-barrio-alto',
      description: 'Dúplex de diseño contemporáneo en edificio rehabilitado. Combina la arquitectura tradicional con acabados modernos. Dos plantas con distribución perfecta.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.DUPLEX,
      price: 195000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.BARRIO_ALTO.name,
      address: 'Calle Regina 34',
      latitude: randomOffset(BARRIOS.BARRIO_ALTO.lat),
      longitude: randomOffset(BARRIOS.BARRIO_ALTO.lng),
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 120,
      builtYear: 2020,
      floor: 2,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Local comercial junto a Plaza del Cabildo',
      slug: 'local-plaza-cabildo',
      description: 'Local comercial en zona de máximo tránsito. Ideal para comercio, hostelería o servicios. Gran escaparate y almacén. Zona muy concurrida todo el año.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.COMMERCIAL,
      price: 800,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.BARRIO_ALTO.name,
      address: 'Plaza del Cabildo 3',
      latitude: randomOffset(BARRIOS.BARRIO_ALTO.lat),
      longitude: randomOffset(BARRIOS.BARRIO_ALTO.lng),
      areaM2: 85,
      builtYear: 1985,
      floor: 0,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      energyRating: 'E',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },

    // === LA JARA (zona residencial moderna) ===
    {
      title: 'Chalet independiente con piscina en La Jara',
      slug: 'chalet-piscina-la-jara',
      description: 'Espectacular chalet independiente en la mejor zona de La Jara. Parcela de 500m², piscina privada, jardín con riego automático y barbacoa. Garaje para 2 coches.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.HOUSE,
      price: 385000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.LA_JARA.name,
      address: 'Urbanización La Jara, 45',
      latitude: randomOffset(BARRIOS.LA_JARA.lat),
      longitude: randomOffset(BARRIOS.LA_JARA.lng),
      bedrooms: 4,
      bathrooms: 3,
      areaM2: 220,
      builtYear: 2012,
      hasElevator: false,
      hasParking: true,
      hasPool: true,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Adosado en La Jara con jardín',
      slug: 'adosado-la-jara-jardin',
      description: 'Bonito adosado en urbanización cerrada con piscina comunitaria. Jardín privado de 60m², solarium en azotea. Zona tranquila perfecta para familias.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.HOUSE,
      price: 225000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.LA_JARA.name,
      address: 'Calle Jazmín 12',
      latitude: randomOffset(BARRIOS.LA_JARA.lat),
      longitude: randomOffset(BARRIOS.LA_JARA.lng),
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 145,
      builtYear: 2008,
      hasElevator: false,
      hasParking: true,
      hasPool: true,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Piso nuevo a estrenar en La Jara',
      slug: 'piso-nuevo-la-jara',
      description: 'Piso de obra nueva en promoción recién terminada. Calidades premium, cocina amueblada, aire acondicionado por conductos. Plaza de garaje y trastero incluidos.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 165000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.LA_JARA.name,
      address: 'Avenida de la Jara 78',
      latitude: randomOffset(BARRIOS.LA_JARA.lat),
      longitude: randomOffset(BARRIOS.LA_JARA.lng),
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 100,
      builtYear: 2024,
      floor: 1,
      hasElevator: true,
      hasParking: true,
      hasPool: true,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'A',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Apartamento en alquiler La Jara',
      slug: 'apartamento-alquiler-la-jara',
      description: 'Apartamento completamente amueblado listo para entrar a vivir. Urbanización con piscina, pádel y zonas verdes. Ideal para familias o parejas.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.APARTMENT,
      price: 650,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.LA_JARA.name,
      address: 'Calle Olivo 5',
      latitude: randomOffset(BARRIOS.LA_JARA.lat),
      longitude: randomOffset(BARRIOS.LA_JARA.lng),
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 70,
      builtYear: 2016,
      floor: 2,
      hasElevator: true,
      hasParking: true,
      hasPool: true,
      hasTerrace: false,
      hasGarden: false,
      furnished: true,
      petsAllowed: false,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },

    // === MARTÍN MIGUEL (zona céntrica tradicional) ===
    {
      title: 'Piso reformado en Martín Miguel',
      slug: 'piso-reformado-martin-miguel',
      description: 'Piso totalmente reformado en zona muy céntrica. A 2 minutos del mercado de abastos y de la Plaza del Cabildo. Cocina y baños nuevos, suelos de gres.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 115000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.MARTIN_MIGUEL.name,
      address: 'Calle Banda Playa 56',
      latitude: randomOffset(BARRIOS.MARTIN_MIGUEL.lat),
      longitude: randomOffset(BARRIOS.MARTIN_MIGUEL.lng),
      bedrooms: 3,
      bathrooms: 1,
      areaM2: 85,
      builtYear: 2019,
      floor: 3,
      hasElevator: true,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Casa con patio en Martín Miguel',
      slug: 'casa-patio-martin-miguel',
      description: 'Casa de pueblo con encanto, patio interior con plantas y solarium en azotea. Ubicación inmejorable para vivir el auténtico Sanlúcar. Posibilidad de segregar.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.HOUSE,
      price: 175000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.MARTIN_MIGUEL.name,
      address: 'Calle Trasbolsa 14',
      latitude: randomOffset(BARRIOS.MARTIN_MIGUEL.lat),
      longitude: randomOffset(BARRIOS.MARTIN_MIGUEL.lng),
      bedrooms: 4,
      bathrooms: 2,
      areaM2: 130,
      builtYear: 1960,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'E',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Piso económico en Martín Miguel',
      slug: 'piso-economico-martin-miguel',
      description: 'Oportunidad única: piso a reformar en excelente ubicación. Posibilidad de personalizar a tu gusto. Ideal para inversores o primera vivienda con presupuesto ajustado.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 68000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.MARTIN_MIGUEL.name,
      address: 'Calle Divina Pastora 8',
      latitude: randomOffset(BARRIOS.MARTIN_MIGUEL.lat),
      longitude: randomOffset(BARRIOS.MARTIN_MIGUEL.lng),
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 60,
      builtYear: 1975,
      floor: 2,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'G',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Alquiler temporal centro Martín Miguel',
      slug: 'alquiler-temporal-martin-miguel',
      description: 'Piso amueblado disponible para alquiler de temporada o larga estancia. Perfecto para profesionales desplazados. Todo incluido: wifi, agua, luz (límite razonable).',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.FLAT,
      price: 500,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.MARTIN_MIGUEL.name,
      address: 'Calle Cristóbal Colón 22',
      latitude: randomOffset(BARRIOS.MARTIN_MIGUEL.lat),
      longitude: randomOffset(BARRIOS.MARTIN_MIGUEL.lng),
      bedrooms: 1,
      bathrooms: 1,
      areaM2: 45,
      builtYear: 2000,
      floor: 1,
      hasElevator: false,
      hasParking: false,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: true,
      petsAllowed: false,
      energyRating: 'D',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },

    // === EL PINO (zona cercana a la playa de La Calzada) ===
    {
      title: 'Chalet pareado en El Pino',
      slug: 'chalet-pareado-el-pino',
      description: 'Fantástico chalet pareado a 10 minutos andando de la playa de La Calzada. Jardín privado, garaje y trastero. Zona muy tranquila y familiar.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.HOUSE,
      price: 275000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.EL_PINO.name,
      address: 'Calle Pino 34',
      latitude: randomOffset(BARRIOS.EL_PINO.lat),
      longitude: randomOffset(BARRIOS.EL_PINO.lng),
      bedrooms: 4,
      bathrooms: 2,
      areaM2: 180,
      builtYear: 2005,
      hasElevator: false,
      hasParking: true,
      hasPool: false,
      hasTerrace: true,
      hasGarden: true,
      furnished: false,
      petsAllowed: true,
      energyRating: 'C',
      status: PropertyStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: 'Piso con garaje en El Pino',
      slug: 'piso-garaje-el-pino',
      description: 'Piso exterior muy luminoso con plaza de garaje incluida. Zona muy demandada por su cercanía a la playa y todos los servicios. Comunidad con piscina.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.FLAT,
      price: 145000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.EL_PINO.name,
      address: 'Avenida del Pino 89',
      latitude: randomOffset(BARRIOS.EL_PINO.lat),
      longitude: randomOffset(BARRIOS.EL_PINO.lng),
      bedrooms: 3,
      bathrooms: 2,
      areaM2: 95,
      builtYear: 2010,
      floor: 2,
      hasElevator: true,
      hasParking: true,
      hasPool: true,
      hasTerrace: true,
      hasGarden: false,
      furnished: false,
      petsAllowed: true,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Bajo con jardín en El Pino',
      slug: 'bajo-jardin-el-pino',
      description: 'Planta baja con jardín privado de 50m². Acceso directo desde el jardín a zonas comunes con piscina. Perfecto para familias con niños o mascotas.',
      operation: OperationType.RENT,
      propertyType: PropertyCategory.FLAT,
      price: 700,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.EL_PINO.name,
      address: 'Calle Almendro 7',
      latitude: randomOffset(BARRIOS.EL_PINO.lat),
      longitude: randomOffset(BARRIOS.EL_PINO.lng),
      bedrooms: 2,
      bathrooms: 1,
      areaM2: 75,
      builtYear: 2015,
      floor: 0,
      hasElevator: false,
      hasParking: true,
      hasPool: true,
      hasTerrace: false,
      hasGarden: true,
      furnished: true,
      petsAllowed: true,
      energyRating: 'B',
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: 'Garaje cerrado en El Pino',
      slug: 'garaje-cerrado-el-pino',
      description: 'Plaza de garaje cerrada en edificio con seguridad 24h. Fácil acceso y maniobra. Ideal para complementar vivienda en la zona o como inversión.',
      operation: OperationType.SALE,
      propertyType: PropertyCategory.GARAGE,
      price: 18000,
      cityId: sanlucar.id,
      neighborhood: BARRIOS.EL_PINO.name,
      address: 'Calle Naranjo 15',
      latitude: randomOffset(BARRIOS.EL_PINO.lat),
      longitude: randomOffset(BARRIOS.EL_PINO.lng),
      areaM2: 25,
      builtYear: 2012,
      hasElevator: false,
      hasParking: true,
      hasPool: false,
      hasTerrace: false,
      hasGarden: false,
      furnished: false,
      petsAllowed: false,
      status: PropertyStatus.ACTIVE,
      isFeatured: false,
    },
  ];

  // Crear propiedades
  console.log('📝 Creando 20 propiedades en Sanlúcar de Barrameda...\n');

  for (const property of properties) {
    try {
      const created = await prisma.property.create({
        data: property,
      });
      const priceStr = created.operation === 'SALE'
        ? `€${created.price.toLocaleString()}`
        : `€${created.price}/mes`;
      console.log(`✅ [${created.neighborhood}] ${created.title} - ${priceStr}`);
    } catch (error: any) {
      if (error.code === 'P2002') {
        console.log(`⚠️  ${property.title} - Ya existe (slug duplicado)`);
      } else {
        console.error(`❌ Error al crear ${property.title}:`, error.message);
      }
    }
  }

  // Resumen
  const featuredCount = properties.filter(p => p.isFeatured).length;
  const saleCount = properties.filter(p => p.operation === OperationType.SALE).length;
  const rentCount = properties.filter(p => p.operation === OperationType.RENT).length;

  console.log('\n✅ Seed completado!');
  console.log('📊 Resumen:');
  console.log(`   - Total propiedades: ${properties.length}`);
  console.log(`   - Propiedades destacadas: ${featuredCount}`);
  console.log(`   - En venta: ${saleCount}`);
  console.log(`   - En alquiler: ${rentCount}`);
  console.log('\n🗺️ Barrios incluidos:');
  Object.values(BARRIOS).forEach(b => {
    const count = properties.filter(p => p.neighborhood === b.name).length;
    console.log(`   - ${b.name}: ${count} propiedades`);
  });
}

main()
  .catch((e) => {
    console.error('❌ Error durante el seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
